server {
    listen 8080;
    root www;

    location / {
        methods GET;
        index index.html;
    }

    location /upload {
        methods GET POST;
        root uploads;
    }
}

server {
    listen 8081;
    root admin;

    location / {
        methods GET;
        index admin.html;
    }
}
