server {
    listen 8080;
    root www;
    client_max_body_size 10m;
    error_page  error.html;
	

    location / {
        methods GET;
        index index.html; // only use when discover the URI/path is a directory, then we can add index to behind as an static file return

    }

    location /upload {
        methods GET POST;
        root uploads; // should be www? otherwise its uploads/upload, no www will be added into url
    }
}

server {
    listen 8081;
    root admin;

    location / {
        methods GET;
        index admin.html;
    }
}

server {
    listen 8082;
    root admin;

    location / {
        methods GET;
        index admin.html;
    }
}