server {
    listen 8080;
    root www;
    client_max_body_size 10m;
    error_page  error.html;
	server_name	somename;

    location / {
        methods GET;
        index index.html;
		autoindex on;
    }

    location /upload {
        methods GET POST;
        upload_store uploads;
		client_max_body_size	20m;
    }

	location /cgi-bin {
		methods GET POST;
		root www;
		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/php-cgi;
	}
}

#struct LocationConfig
#{
#	std::string path;
#	std::vector<std::string> methods;
#	std::string root;
#	std::string index;

#	bool autoindex;

#	std::string uploadStore;

#	std::map<std::string, std::string> cgiHandlers;

#	bool redirectEnabled;
#	int redirectStatus;
#	std::string redirectTarget;
#}

#cgiHandlers[".py"] = "/usr/bin/python3"